name: flaskr test coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test flaskr
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests and collect coverage
      run: pytest --cov=./flaskr/ --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
